### ISSUE TITLE
BE: Modify User Creation route

### ISSUE THREAD

**Issue by sina-jamshidi** [hatchways/team-yugioh#10]
on Creation of user, create an initial Event Type for a 60 min duration (this is default)

**Comment by WhoaNellie** [comment]
Just realized I currently have this solved on the front-end by giving all users 15/30/60 min events by default, should I refactor it to be created on the backend when they sign up?

**Comment by WhoaNellie** [comment]
Oh, but we'll want to link the appointments to the event ids

**Comment by WhoaNellie** [comment]
Should there be 15/30/60 default events like in the mocs?
