### ISSUE TITLE
Bug: handle white space in URL

### ISSUE THREAD

**Issue by alvyjudy** [hatchways/team-yugioh#121]
It looks like the URL is still valid when it contains white space, which leads to issue when browser sees it. Shouldn't be a hard fix but there seem to be multiple approach to it.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/53921639/106531301-fa8ae280-64bb-11eb-8b00-5c13d0812496.png">
<img width="410" alt="image" src="https://user-images.githubusercontent.com/53921639/106531365-142c2a00-64bc-11eb-93ab-f39306e85bc3.png">

**Comment by WhoaNellie** [comment]
I think it'd be easiest to encodeURI while writing to the db and checking unique
