### ISSUE TITLE
unique link checking always shows link is unique

### ISSUE THREAD

**Issue by WhoaNellie** [hatchways/team-yugioh#142]
When trying to put in urls already taken it always show it's available even when it's taken
![image](https://user-images.githubusercontent.com/8296126/106709388-4a93a300-65a9-11eb-82db-7ed65f72724a.png)

**Comment by alvyjudy** [comment]
Examining the backend console, it looks like the `/api/event/is_unique` is not receiving any request when I type in the URL box. There seems to be some issue with the debouncing logic. @kozaktar any hints?
