### ISSUE TITLE
Warnings in Console

### ISSUE THREAD

**Issue by WhoaNellie** [hatchways/team-yugioh#146]
![image](https://user-images.githubusercontent.com/8296126/106711484-71070d80-65ac-11eb-9960-d4b097e5fc39.png)

**Comment by alvyjudy** [comment]
Upon closer look, I realize most of it are from @kozaktar 's recent PR. Do you mind fixing those actually lol

**Comment by WhoaNellie** [comment]
![image](https://user-images.githubusercontent.com/8296126/106782613-367a9080-65ff-11eb-97a8-42feb28c6e7c.png)
This one popped up too

**Comment by WhoaNellie** [comment]
Most of this is due to this issue https://github.com/hatchways/team-yugioh/issues/138
