### ISSUE TITLE
Set up: Email API (Sendgrid)

### ISSUE THREAD

**Issue by sina-jamshidi** [hatchways/team-yugioh#26]
https://sendgrid.com/solutions/email-api/

**Comment by WhoaNellie** [comment]
Their email API has been under maintenance since the 12th, I hope it's still functional in some way for me to test! 
https://status.sendgrid.com/
![image](https://user-images.githubusercontent.com/8296126/105249056-55235680-5b2c-11eb-97bb-a1bce29d6b5b.png)
